#!/usr/bin/env python3
"""
Example: Add transition between clips
Generated by: video-editor skill - Script Generator
"""

import opentimelineio as otio
from pathlib import Path


def get_track_by_name_or_index(timeline, track):
    """Get track by name or index (0-based)."""
    if isinstance(track, int):
        if track < len(timeline.tracks):
            return timeline.tracks[track]
        raise IndexError(f"Track index {track} out of range")
    for t in timeline.tracks:
        if t.name == track:
            return t
    raise ValueError(f"Track not found: {track}")


# ============================================================================
# MAIN SCRIPT
# ============================================================================

# Load timeline
project_file = "public/projects/sample/project.otio"
if not Path(project_file).exists():
    print(f"✗ Project file not found: {project_file}")
    exit(1)

timeline = otio.adapters.read_from_file(project_file)
print(f"✓ Loaded timeline: {timeline.name}")
print(f"  Tracks: {len(timeline.tracks)}")
for i, track in enumerate(timeline.tracks):
    print(f"    {i}: {track.name} ({len(track)} items)")

# Add 2s transition between clips 2-3 on track 0
track = get_track_by_name_or_index(timeline, 0)

if 3 < len(track):
    transition = otio.schema.Transition(
        transition_type=otio.schema.TransitionTypes.SMPTE_Dissolve,
        in_offset=otio.opentime.from_seconds(1.0),
        out_offset=otio.opentime.from_seconds(1.0)
    )
    track.insert(3, transition)
    print(f"✓ Added 2.0s transition between clips 2-3")
else:
    print(f"✗ Clip index 3 out of range")

# Save timeline
otio.adapters.write_to_file(timeline, project_file)
print("✓ Timeline saved successfully")
