#!/usr/bin/env python3
"""
Example: Insert clip into timeline
Generated by: video-editor skill - Script Generator
"""

import opentimelineio as otio
from pathlib import Path


def get_track_by_name_or_index(timeline, track):
    """Get track by name or index (0-based)."""
    if isinstance(track, int):
        if track < len(timeline.tracks):
            return timeline.tracks[track]
        raise IndexError(f"Track index {track} out of range")
    for t in timeline.tracks:
        if t.name == track:
            return t
    raise ValueError(f"Track not found: {track}")


def find_clip_index_at_time(track, time_sec: float) -> int:
    """Find clip index at specific time position (in seconds)."""
    current_time = 0.0
    for i, item in enumerate(track):
        if current_time >= time_sec:
            return i
        if hasattr(item, 'duration'):
            current_time += item.duration().to_seconds()
    return len(track)


def create_clip_from_url(url: str, name: str, duration_sec: float):
    """Create OTIO clip from URL."""
    return otio.schema.Clip(
        name=name,
        media_reference=otio.schema.ExternalReference(target_url=url),
        source_range=otio.opentime.TimeRange(
            start_time=otio.opentime.from_seconds(0),
            duration=otio.opentime.from_seconds(duration_sec)
        )
    )


# ============================================================================
# MAIN SCRIPT
# ============================================================================

# Load timeline
project_file = "public/projects/sample/project.otio"
if not Path(project_file).exists():
    print(f"✗ Project file not found: {project_file}")
    exit(1)

timeline = otio.adapters.read_from_file(project_file)
print(f"✓ Loaded timeline: {timeline.name}")
print(f"  Tracks: {len(timeline.tracks)}")
for i, track in enumerate(timeline.tracks):
    print(f"    {i}: {track.name} ({len(track)} items)")

# Insert clip at 10s on track 0
track = get_track_by_name_or_index(timeline, 0)
clip = otio.schema.Clip(
    name="Inserted Clip",
    media_reference=otio.schema.ExternalReference(target_url="video.mp4"),
    source_range=otio.opentime.TimeRange(
        start_time=otio.opentime.from_seconds(0),
        duration=otio.opentime.from_seconds(5.0)
    )
)
# Find insertion point at time 10s
insert_index = find_clip_index_at_time(track, 10.0)
track.insert(insert_index, clip)
print(f"✓ Inserted clip at {insert_index}")

# Save timeline
otio.adapters.write_to_file(timeline, project_file)
print("✓ Timeline saved successfully")
