#!/usr/bin/env python3
"""
Example: Add intro and outro to video
Generated by: video-editor skill - Script Generator
"""

import opentimelineio as otio
from pathlib import Path


def get_track_by_name_or_index(timeline, track):
    """Get track by name or index (0-based)."""
    if isinstance(track, int):
        if track < len(timeline.tracks):
            return timeline.tracks[track]
        raise IndexError(f"Track index {track} out of range")
    for t in timeline.tracks:
        if t.name == track:
            return t
    raise ValueError(f"Track not found: {track}")


# ============================================================================
# INTRO/OUTRO WORKFLOW
# ============================================================================

# Load timeline
timeline = otio.adapters.read_from_file("public/projects/sample/project.otio")
print(f"✓ Loaded timeline: {timeline.name}")

print("Adding intro and outro...")

# 1. Create intro clip
intro = otio.schema.Clip(
    name="Intro",
    media_reference=otio.schema.ExternalReference(target_url="public/videos/intro.mp4"),
    source_range=otio.opentime.TimeRange(
        start_time=otio.opentime.from_seconds(0),
        duration=otio.opentime.from_seconds(3.0)
    )
)

# 2. Create outro clip
outro = otio.schema.Clip(
    name="Outro",
    media_reference=otio.schema.ExternalReference(target_url="public/videos/outro.mp4"),
    source_range=otio.opentime.TimeRange(
        start_time=otio.opentime.from_seconds(0),
        duration=otio.opentime.from_seconds(3.0)
    )
)

# 3. Insert intro at beginning of main video track
if len(timeline.tracks) > 0:
    main_track = timeline.tracks[0]
    main_track.insert(0, intro)
    print("✓ Added intro")

    # 4. Append outro at end
    main_track.append(outro)
    print("✓ Added outro")

    # 5. Extend other tracks with gaps to maintain sync
    intro_duration_val = intro.duration().to_seconds()
    outro_duration_val = outro.duration().to_seconds()

    for i, track in enumerate(timeline.tracks):
        if i == 0:  # Skip main track
            continue

        # Add gap at beginning
        gap_start = otio.schema.Gap(
            duration=otio.opentime.from_seconds(intro_duration_val)
        )
        track.insert(0, gap_start)

        # Add gap at end
        gap_end = otio.schema.Gap(
            duration=otio.opentime.from_seconds(outro_duration_val)
        )
        track.append(gap_end)

    print(f"✓ Extended {len(timeline.tracks) - 1} tracks with gaps")
    print("✓ Intro/outro workflow complete")
else:
    print("✗ Timeline has no tracks")

# Save timeline
otio.adapters.write_to_file(timeline, "public/projects/sample/project.otio")
print("✓ Timeline saved successfully")
